# Generated by Django 5.0.2 on 2024-02-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
